<?php
$PRODUCTOS = [
    // HOME / DESTACADOS
    1  => ['id'=>1,  'nombre'=>'Grand Court Cloudfoam Blanco', 'marca'=>'ADIDAS', 'desc'=>'Zapatillas unisex',              'precio'=>199.99, 'imagen'=>'IMG/productos/adidas-grand-court.avif'],
    2  => ['id'=>2,  'nombre'=>"Air Force 1 Low White '07",    'marca'=>'NIKE',   'desc'=>'Zapatillas unisex',              'precio'=>299.99, 'imagen'=>'IMG/productos/nike-air-force-1.webp'],
    3  => ['id'=>3,  'nombre'=>'Suede XL Black/White',          'marca'=>'PUMA',   'desc'=>'Zapatillas unisex',              'precio'=>349.99, 'imagen'=>'IMG/productos/puma-suede-xl.avif'],
    4  => ['id'=>4,  'nombre'=>'Superstar Cloud White',          'marca'=>'ADIDAS', 'desc'=>'Zapatillas unisex',              'precio'=>299.99, 'imagen'=>'IMG/productos/adidas-superstar.avif'],
    5  => ['id'=>5,  'nombre'=>'Dunk Low Panda',                 'marca'=>'NIKE',   'desc'=>'Zapatillas unisex',              'precio'=>299.99, 'imagen'=>'IMG/productos/nike-dunk-panda.webp'],
    6  => ['id'=>6,  'nombre'=>'Forum Low Blanco',               'marca'=>'ADIDAS', 'desc'=>'Zapatillas unisex',              'precio'=>299.99, 'imagen'=>'IMG/productos/adidas-forum-low.avif'],
    7  => ['id'=>7,  'nombre'=>'Old Skool Black',                'marca'=>'VANS',   'desc'=>'Zapatillas unisex',              'precio'=>249.99, 'imagen'=>'IMG/productos/vans-old-skool-black.png'],
    8  => ['id'=>8,  'nombre'=>'Samba OG Negro',                 'marca'=>'ADIDAS', 'desc'=>'Zapatillas unisex',              'precio'=>319.99, 'imagen'=>'IMG/productos/adidas-samba-og.avif'],
    9  => ['id'=>9,  'nombre'=>'Dunk High Panda',                'marca'=>'NIKE',   'desc'=>'Zapatillas unisex',              'precio'=>349.99, 'imagen'=>'IMG/productos/nike-dunk-high-panda.jpeg'],
    10 => ['id'=>10, 'nombre'=>"Dunk Valentine's Day",           'marca'=>'NIKE',   'desc'=>'Zapatillas unisex',              'precio'=>349.99, 'imagen'=>'IMG/productos/nike-dunk-valentine.jpeg'],
    11 => ['id'=>11, 'nombre'=>'Dunk SB Black',                  'marca'=>'NIKE',   'desc'=>'Zapatillas unisex',              'precio'=>279.99, 'imagen'=>'IMG/productos/nike-dunk-sb-black.jpeg'],
    12 => ['id'=>12, 'nombre'=>'Dunk SB Taupe Haze',             'marca'=>'NIKE',   'desc'=>'Zapatillas unisex',              'precio'=>279.99, 'imagen'=>'IMG/productos/nike-dunk-sb-taupe.jpeg'],
    // HOMBRE BAJO
    101 => ['id'=>101, 'nombre'=>'Nike Court Royale 2 Next Nature',  'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>269.90, 'imagen'=>'IMG/Hombre/preciobajo/nike1.webp'],
    102 => ['id'=>102, 'nombre'=>'Nike Court Royale 2 Next Nature',  'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>269.90, 'imagen'=>'IMG/Hombre/preciobajo/nike2.webp'],
    103 => ['id'=>103, 'nombre'=>'Nike Court Vision Low Next Nature', 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>299.90, 'imagen'=>'IMG/Hombre/preciobajo/nike3.webp'],
    104 => ['id'=>104, 'nombre'=>'Nike Court Vision Low Next Nature', 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>299.90, 'imagen'=>'IMG/Hombre/preciobajo/nike4.webp'],
    105 => ['id'=>105, 'nombre'=>'Nike Calm',                         'marca'=>'NIKE', 'desc'=>'Zapatillas tipo mule para hombre', 'precio'=>249.90, 'imagen'=>'IMG/Hombre/preciobajo/nike5.webp'],
    106 => ['id'=>106, 'nombre'=>'Nike Calm',                         'marca'=>'NIKE', 'desc'=>'Zapatillas Urbano Hombre', 'precio'=>249.90, 'imagen'=>'IMG/Hombre/preciobajo/nike6.webp'],
    // HOMBRE MEDIO
    107 => ['id'=>107, 'nombre'=>"Nike Air Force 1 '07", 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>529.90, 'imagen'=>'IMG/Hombre/preciomedio/nike1.webp'],
    108 => ['id'=>108, 'nombre'=>"Nike Air Force 1 '07", 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>529.90, 'imagen'=>'IMG/Hombre/preciomedio/nike2.webp'],
    109 => ['id'=>109, 'nombre'=>"Nike Air Force 1 '07", 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>529.90, 'imagen'=>'IMG/Hombre/preciomedio/nike3.webp'],
    110 => ['id'=>110, 'nombre'=>"Nike Air Force 1 '07", 'marca'=>'NIKE', 'desc'=>'Zapatillas Urbano Hombre','precio'=>529.90, 'imagen'=>'IMG/Hombre/preciomedio/nike4.webp'],
    111 => ['id'=>111, 'nombre'=>'Nike Air Max AP',       'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>469.90, 'imagen'=>'IMG/Hombre/preciomedio/nike5.webp'],
    112 => ['id'=>112, 'nombre'=>'Nike Air Max AP',       'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>469.90, 'imagen'=>'IMG/Hombre/preciomedio/nike6.webp'],
    // HOMBRE ALTO
    113 => ['id'=>113, 'nombre'=>'Nike Dunk Low Retro', 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>569.90, 'imagen'=>'IMG/Hombre/precioalto/nike1.webp'],
    114 => ['id'=>114, 'nombre'=>'Nike Dunk Low Retro', 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>569.90, 'imagen'=>'IMG/Hombre/precioalto/nike2.webp'],
    115 => ['id'=>115, 'nombre'=>'Nike Dunk Low Retro', 'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>569.90, 'imagen'=>'IMG/Hombre/precioalto/nike3.webp'],
    116 => ['id'=>116, 'nombre'=>'Nike Air Max Dn',     'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>629.90, 'imagen'=>'IMG/Hombre/precioalto/nike4.webp'],
    117 => ['id'=>117, 'nombre'=>'Nike Air Max Dn',     'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>699.90, 'imagen'=>'IMG/Hombre/precioalto/nike5.webp'],
    118 => ['id'=>118, 'nombre'=>'Nike Air Max Dn',     'marca'=>'NIKE', 'desc'=>'Zapatillas para hombre', 'precio'=>699.90, 'imagen'=>'IMG/Hombre/precioalto/nike6.webp'],
    // MUJER BAJO
    201 => ['id'=>201, 'nombre'=>'Nike Court Legacy Next Nature', 'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>259.90, 'imagen'=>'IMG/Mujer/preciobajo/nike1.webp'],
    202 => ['id'=>202, 'nombre'=>'Nike Court Legacy Next Nature', 'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>259.90, 'imagen'=>'IMG/Mujer/preciobajo/nike2.webp'],
    203 => ['id'=>203, 'nombre'=>'Nike Court Legacy Next Nature', 'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>259.90, 'imagen'=>'IMG/Mujer/preciobajo/nike3.webp'],
    204 => ['id'=>204, 'nombre'=>'Nike Court Royale 2',           'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>229.90, 'imagen'=>'IMG/Mujer/preciobajo/nike4.webp'],
    205 => ['id'=>205, 'nombre'=>'Nike Court Royale 2',           'marca'=>'NIKE', 'desc'=>'Zapatillas tipo mule para mujer', 'precio'=>229.90, 'imagen'=>'IMG/Mujer/preciobajo/nike5.webp'],
    206 => ['id'=>206, 'nombre'=>'Nike Court Royale 2',           'marca'=>'NIKE', 'desc'=>'Zapatillas Urbano mujer', 'precio'=>229.90, 'imagen'=>'IMG/Mujer/preciobajo/nike6.webp'],
    // MUJER MEDIO
    207 => ['id'=>207, 'nombre'=>"Nike Air Force 1 '07 SE", 'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>529.90, 'imagen'=>'IMG/Mujer/preciomedio/nike1.webp'],
    208 => ['id'=>208, 'nombre'=>"Nike Air Force 1 '07",    'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>529.90, 'imagen'=>'IMG/Mujer/preciomedio/nike2.webp'],
    209 => ['id'=>209, 'nombre'=>"Nike Air Force 1 '07",    'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>529.90, 'imagen'=>'IMG/Mujer/preciomedio/nike3.webp'],
    210 => ['id'=>210, 'nombre'=>'Nike Air Force 1 07 SE',  'marca'=>'NIKE', 'desc'=>'Zapatillas Urbano mujer', 'precio'=>529.90, 'imagen'=>'IMG/Mujer/preciomedio/nike4.webp'],
    211 => ['id'=>211, 'nombre'=>'Nike Air Force 1 07 SE',  'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>529.90, 'imagen'=>'IMG/Mujer/preciomedio/nike5.webp'],
    212 => ['id'=>212, 'nombre'=>'Nike Air Force 1 07 SE',  'marca'=>'NIKE', 'desc'=>'Zapatillas para mujer', 'precio'=>529.90, 'imagen'=>'IMG/Mujer/preciomedio/nike6.webp'],
    // MUJER ALTO
    213 => ['id'=>213, 'nombre'=>'Nike Dunk High',   'marca'=>'NIKE',   'desc'=>'Zapatillas para mujer', 'precio'=>639.90, 'imagen'=>'IMG/Mujer/precioalto/nike1.webp'],
    214 => ['id'=>214, 'nombre'=>'Nike Dunk High',   'marca'=>'NIKE',   'desc'=>'Zapatillas para mujer', 'precio'=>639.90, 'imagen'=>'IMG/Mujer/precioalto/nike2.webp'],
    215 => ['id'=>215, 'nombre'=>'Nike Dunk High',   'marca'=>'NIKE',   'desc'=>'Zapatillas para mujer', 'precio'=>639.90, 'imagen'=>'IMG/Mujer/precioalto/nike3.webp'],
    216 => ['id'=>216, 'nombre'=>'Nike Dunk High',   'marca'=>'NIKE',   'desc'=>'Zapatillas para mujer', 'precio'=>639.90, 'imagen'=>'IMG/Mujer/precioalto/nike4.webp'],
    217 => ['id'=>217, 'nombre'=>'Air Jordan 1 Low', 'marca'=>'JORDAN', 'desc'=>'Zapatillas para mujer', 'precio'=>579.90, 'imagen'=>'IMG/Mujer/precioalto/nike5.webp'],
    218 => ['id'=>218, 'nombre'=>'Air Jordan 1 Low', 'marca'=>'JORDAN', 'desc'=>'Zapatillas para mujer', 'precio'=>579.90, 'imagen'=>'IMG/Mujer/precioalto/nike6.webp'],
    // SALE
    301 => ['id'=>301, 'nombre'=>'Nike Everyday Essential',        'marca'=>'NIKE',   'desc'=>'Medias',                                    'precio'=>59.90, 'imagen'=>'IMG/sale/nike1.webp'],
    302 => ['id'=>302, 'nombre'=>'Nike Everyday Essential',        'marca'=>'NIKE',   'desc'=>'Medias',                                    'precio'=>69.90, 'imagen'=>'IMG/sale/nike2.webp'],
    303 => ['id'=>303, 'nombre'=>'Jordan Everyday',                'marca'=>'JORDAN', 'desc'=>'Medias',                                    'precio'=>69.90, 'imagen'=>'IMG/sale/nike3.webp'],
    304 => ['id'=>304, 'nombre'=>'Nike Sportswear',                'marca'=>'NIKE',   'desc'=>'Short para niño talla grande',              'precio'=>59.90, 'imagen'=>'IMG/sale/nike4.webp'],
    305 => ['id'=>305, 'nombre'=>'Jordan Medias Everyday',         'marca'=>'JORDAN', 'desc'=>'Medias al tobillo Everyday',                'precio'=>69.90, 'imagen'=>'IMG/sale/nike5.webp'],
    306 => ['id'=>306, 'nombre'=>'Nike Everyday Plus Lightweight', 'marca'=>'NIKE',   'desc'=>'Medias cortas de entrenamiento para mujer', 'precio'=>49.90, 'imagen'=>'IMG/sale/nike6.webp'],
];
